import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import { TrialsProvider } from '../components/providers/TrialsProvider'
import { useEffect, useState } from 'react'
import Display from '../components/Display'

export default function Home() {

  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    setLoaded(true)
  }, [])

  if (loaded) {
    return (
      <>
        <Head>
          <title>はまったいまー</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <SessionProvider>
          <TrialsProvider>
            <Display/>
          </TrialsProvider>
        </SessionProvider>
      </>
    )
  } else {
    return (
      <></>
    )
  }
}
