import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import { FormProvider, useForm } from 'react-hook-form'
import { useStopwatch } from 'react-timer-hook'
import { MarkdownProvider } from '../components/providers/MarkdownProvider'
import Navbar from '../components/Navbar'
import Preview from '../components/Preview'
import Issue from '../components/Issue'
import Trials from '../components/Trials'

export default function Home() {
  const { seconds, minutes, hours, days, start, pause, isRunning } =
    useStopwatch({
      autoStart: false,
    })

  const methods = useForm({
    mode: 'onBlur',
    defaultValues: {
      'tobe': '',
      'asis': '',
      'problem': '',
      'limit': '30',
    },
  })

  return (
    <>
      <Head>
        <title>はまったいまー</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <SessionProvider>
        <MarkdownProvider>
          <FormProvider {...methods}>
            <Navbar
              isRunning={isRunning}
              seconds={seconds}
              minutes={minutes}
              hours={hours}
              days={days}
              start={start}
              pause={pause}
            />
            <div className={'columns is-gapless'}>
              <div className={'column'}>
                <Issue start={start}/>
                <Trials/>
              </div>
              <div className={'column content'}>
                <Preview/>
              </div>
            </div>
          </FormProvider>
        </MarkdownProvider>
      </SessionProvider>
    </>
  )
}
