import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import { useStopwatch } from 'react-timer-hook'
import { FormProvider, useForm } from 'react-hook-form'
import { MarkdownProvider } from '../components/providers/MarkdownProvider'
import { TrialsProvider } from '../components/providers/TrialsProvider'
import Navbar from '../components/Navbar'
import Preview from '../components/Preview'
import Editor from '../components/Editor'

export default function Home() {

  const watch = useStopwatch({ autoStart: false })

  const methods = useForm({
    mode: 'onBlur',
    defaultValues: {
      'tobe': '',
      'asis': '',
      'problem': '',
      'limit': '30',
    },
  })

  return (
    <>
      <Head>
        <title>はまったいまー</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <SessionProvider>
        <TrialsProvider>
          <FormProvider {...methods}>
            <Navbar watch={watch}/>
          </FormProvider>
          <div className={'columns is-gapless'}>
            <MarkdownProvider>
              <div className={'column'}>
                <Editor methods={methods} watch={watch}/>
              </div>
              <div className={'column content'}>
                <Preview/>
              </div>
            </MarkdownProvider>
          </div>
        </TrialsProvider>
      </SessionProvider>
    </>
  )
}
