import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import { MarkdownProvider } from '../components/providers/MarkdownProvider'
import LoginBtn from '../components/LoginBtn'
import Timer from '../components/Timer'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <SessionProvider>
          <MarkdownProvider>
            <Navbar />
            <LoginBtn />
            <Timer />
          </MarkdownProvider>
        </SessionProvider>
      </div>
    </>
  )
}
