import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import { MarkdownProvider } from '../components/providers/MarkdownProvider'
import Navbar from '../components/Navbar'
import Preview from '../components/Preview'
import Issue from '../components/Issue'
import { useStopwatch } from 'react-timer-hook'

export default function Home() {
  const { seconds, minutes, hours, days, start, pause, isRunning } =
    useStopwatch({
      autoStart: false,
    })

  return (
    <>
      <Head>
        <title>はまったいまー</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider>
        <MarkdownProvider>
          <Navbar
            isRunning={isRunning}
            seconds={seconds}
            minutes={minutes}
            hours={hours}
            days={days}
            start={start}
            pause={pause}
          />
          <div className={'columns is-gapless'}>
            <div className={'column'}>
              <Issue start={start} />
            </div>
            <div className={'column content'}>
              <Preview />
            </div>
          </div>
        </MarkdownProvider>
      </SessionProvider>
    </>
  )
}
