name: Lint
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: ESLint
        run: yarn lint
